name: macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        xcodebuild -scheme AttributedStringBuilder \
        -destination generic/platform=macOS
      
      
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: |
        xcodebuild -scheme AttributedStringBuilder \
        -destination 'platform=OS X,arch=x86_64' \
        test

