name: tvOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: latest-stable
    - uses: actions/checkout@v2
    - name: Build
      run: |
        xcodebuild -scheme AttributedStringBuilder \
        -destination generic/platform=tvOS
      
      
  test:
    runs-on: macos-latest

    steps:
    - uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: latest-stable
    - uses: actions/checkout@v2
    - name: Test
      run: |
        xcodebuild -scheme AttributedStringBuilder \
        -destination 'platform=tvOS Simulator,name=Apple TV 4K,OS=latest' \
        test
